### ISSUE TITLE
指出一些问题

### ISSUE THREAD

**Issue by Nomoax** [GlibWild/ExCollection#5]
一、在ExByte.HasBitValue中：
1、如果枚举值不是Bit中预定义的成员，应抛出异常（建议使用switch语句的default子句来实现）；
2、既然在Bit.Zero分支中通过判断是否不等于0来得到了结果，那么在Bit.One分支中为何不通过判断是否不等于255（byte.MaxValue，二进制值为11111111）来得到结果呢？
二、在ExFile.GetCheckCodeFromFile中：
FileStream实例并未被显式地释放（调用Dispose方法，或者使用using语句）；请注意，从原则上来讲，实现IDisposable的接口都应该显式地释放；
三、在ExFile.GetCheckCodeFromFile中：
应该将SHAxx等实例存储为静态字段，并使用lock语句上锁，因为创建它们的实例的开销是较大的。

**Comment by GlibWild** [comment]
> 

1.HasBitValue的功能是为了获取Byte子节中是否存在指定类型的位，而不是一定会等于255，大于0时都是存在的意思。当然如果没有直接就返回false即可，并不需要抛出异常
2.这个确实写的时候出现了纰漏，1.0.4.8修复
3.本项目基本上都是常用的扩展方法。如果是静态方法，什么时候回收静态字段资源呢？因此这里即用即取，而不是用静态缓存
